### ISSUE TITLE
panic: interface conversion: net.Addr is *net.UnixAddr, not *net.TCPAddr

### ISSUE THREAD

**Issue by zhaoqingliang** [starcoinorg/starcoin-go#20]
I am writing the code of STC test, but panic will be reported。
Code：
func stc() string {
	fmt.Println("stc=====")

	c := client.NewStarcoinClient("https://barnard-seed.starcoin.org")
	fmt.Println("stc=====")

	resource, err := c.GetResource("0x0000000000000000000000000a550c18")
	if err != nil {
		fmt.Println("error:", err)
	}
	fmt.Println("resource:", resource)
	return ""
}

panic: interface conversion: net.Addr is *net.UnixAddr, not *net.TCPAddr

**Comment by wubuku** [comment]
Pull the latest version plz.

I try this test code, and it's ok:

`
func TestStc(t *testing.T) {

	fmt.Println("stc=====")

	c := NewStarcoinClient("https://barnard-seed.starcoin.org")
	fmt.Println("stc=====")

	resource, err := c.GetResource(context.Background(), "0x0000000000000000000000000a550c18")
	if err != nil {
		fmt.Println("error:", err)
	}
	fmt.Println("resource:", resource)
	//return ""
}
`
